"""Builds docs/literature/literature_matrix.csv from manually coded entries.

Coding: Y = present, N = absent, P = partial, NR = not reported in the text we
could access. Every entry's metadata was verified (Crossref DOI record, arXiv
API, HAL, or official proceedings); see candidates_verified.json and
search_raw/. The column `limitations` also states the evidence basis
(full text / abstract / repository README), because several 2026 papers were
paywalled and coded from their abstracts only.
"""
import csv
from pathlib import Path

COLS = ["paper_id", "title", "authors", "year", "venue", "doi", "problem", "dataset", "model", "digital_twin",
        "edge_computing", "multi_agent", "RUL", "uncertainty_quantification", "explainability", "human_in_loop",
        "adaptive_escalation", "latency_evaluation", "communication_evaluation", "limitations",
        "relation_to_HERA_PdM"]

R = [
    ["L01", "Cloud-Edge-Based Lightweight Temporal Convolutional Networks for Remaining Useful Life Prediction in IIoT",
     "L. Ren; Y. Liu; X. Wang; J. Lu; M. J. Deen", 2021, "IEEE Internet of Things Journal 8(16):12578-12587",
     "10.1109/JIOT.2020.3008170", "Cloud-edge RUL prediction", "NR (abstract)", "Lightweight TCN; incremental cloud update",
     "N", "Y", "N", "Y", "N", "N", "N", "N", "Y", "NR",
     "Edge gives fast RUL, cloud refines with history, but both tiers run for every sample; no UQ or routing rule. Basis: abstract",
     "Closest hierarchical RUL architecture; HERA adds calibrated intervals and a decision-driven routing rule"],
    ["L02", "EC-Distill-ZeroDiag: a cloud-edge collaborative framework for zero-shot industrial fault diagnosis via large language model distillation",
     "Z. Yao; Y. Xu; T. Xia; Z. Chen; E. Pan; L. Xi", 2026, "Journal of Intelligent Manufacturing", "10.1007/s10845-026-02897-1",
     "Zero-shot fault diagnosis, edge-cloud", "NR", "LLM-distilled edge student agent + cloud LLM",
     "N", "Y", "Y", "N", "P (self-reflection confidence, uncalibrated)", "P (LLM)", "N", "Y (offloads uncertain patterns)", "NR", "NR",
     "Classification only; uncertainty from agent self-reflection without coverage guarantee. Basis: indexed abstract (publisher-elided in APIs)",
     "Closest 'uncertainty-triggered offloading' in industrial maintenance; HERA uses conformal RUL intervals and decision-sufficiency instead of heuristic confidence"],
    ["L03", "Cloud-Edge-Terminal Collaborative AI Agent for Compound Fault Detection and Diagnosis",
     "Y. He; X. Hu; W. Shen", 2026, "Engineering", "10.1016/j.eng.2026.02.029", "Compound fault detection/diagnosis",
     "NR", "Collaborative AI agent across cloud/edge/terminal", "N", "Y", "Y", "N", "NR", "NR", "NR", "P", "Y", "NR",
     "Diagnosis, not prognosis; reported response-time reduction. Basis: search-engine abstract snippet (full text not accessed)",
     "Agentic cloud-edge-terminal PHM exists; HERA differs in calibrated RUL and safety-bounded escalation"],
    ["L04", "Cloud-Edge-End Collaborative Inference Framework for Efficient Predictive Maintenance in Industrial Internet of Things",
     "Y. Hu; Y. Ma; Y. Zhao; X. He", 2026, "LNNS: Advances in Information, Computing and Technology, pp. 147-160",
     "10.1007/978-3-032-11946-9_13", "PdM with DNN partitioning to reduce delay", "Oil and gas equipment (NR)",
     "Adaptive DNN partitioning", "N", "Y", "N", "NR", "N", "N", "N", "P (partitioning, not uncertainty)", "Y", "P",
     "Routing driven by delay/resource, not predictive uncertainty. Basis: abstract", "Compute-aware PdM offloading; HERA routes by decision risk"],
    ["L05", "Intelligent predictive maintenance: multivariate ML model optimization in an Edge-Fog-Cloud environment",
     "P. Jain; K. K. Mondal; D. Das; A. Khandelwal", 2025, "Computing 107", "10.1007/s00607-025-01585-x",
     "Failure prediction across edge-fog-cloud", "NR", "Bayesian-optimized ML (FogBayes)", "N", "Y", "N", "N", "NR", "N", "N", "N", "NR", "NR",
     "Classification accuracy focus. Basis: abstract snippet", "Edge-fog-cloud PdM placement exists; no calibrated RUL routing"],
    ["L06", "Distributed Predictive Maintenance Through Edge Computing", "R. Rayhana; H. Yun; T. Wang; J. Chen; et al.", 2024,
     "IEEE INDIN 2024, pp. 1-6", "10.1109/INDIN58382.2024.10774467", "Distributed PdM with BaSyx (asset administration shell)",
     "Vehicle data", "PdM algorithms on edge devices + local server", "P (AAS)", "Y", "N", "Y", "N", "N", "N", "N", "NR", "NR",
     "Framework/baseline paper. Basis: abstract", "Edge PdM with RUL but no UQ-driven escalation"],
    ["L07", "HAMA: A Hierarchical Adaptive Multi-Agent Architecture for Industrial IoT Predictive Maintenance",
     "R. B. Saleh; K. P. Dinh; B. Villanyi; T.-S. Hy", 2026, "IEEE Access 14:142595-142613", "10.1109/ACCESS.2026.3731096",
     "Label-scarce anomaly detection + RUL", "Boiler emulator; Wind SCADA; C-MAPSS FD001",
     "Edge z-score pre-filter; fog ensemble consensus; cloud PPO; SHAP; small LM text", "N", "Y", "Y", "Y (point)", "N", "Y (SHAP)", "P (operator text)",
     "P (anomaly pre-filter gate)", "Y", "NR",
     "Edge gate is an anomaly threshold, no RUL interval; PPO adaptation not better than static baseline (authors' own null result). Basis: authors' public repository README",
     "Closest hierarchical multi-agent PdM; its edge gate corresponds to HERA's 'anomaly-trigger' baseline"],
    ["L08", "Self-Evolving Multi-Agent Network for Industrial IoT Predictive Maintenance", "R. Saleh; K. P. Dinh; B. Villanyi; T.-S. Hy",
     2026, "arXiv:2602.16738 (preprint)", "arXiv:2602.16738", "Adaptive anomaly detection across edge/fog/cloud",
     "Boiler emulator; Wind turbine", "Edge pre-filter; fog ensemble voting; cloud PPO; LLM explanations; federated aggregation",
     "N", "Y", "Y", "N", "N", "Y", "P", "P (pre-filtering)", "Y", "NR", "Preprint; anomaly detection only. Basis: abstract",
     "Hierarchical agentic PdM without RUL or calibrated uncertainty"],
    ["L09", "Reliable Inference in Edge-Cloud Model Cascades via Conformal Alignment", "J. Huang; S. Park; N. Paoletti; O. Simeone",
     2025, "arXiv:2510.17543 (preprint)", "arXiv:2510.17543", "Edge-to-cloud deferral with conditional coverage guarantees",
     "Generic classification benchmarks", "Conformal alignment + multiple hypothesis testing", "N", "Y", "N", "N", "Y (conformal)", "N", "N", "Y", "N", "N",
     "Classification prediction sets; not maintenance, no RUL or decision regions. Basis: abstract",
     "Closest methodological prior art for conformal escalation; HERA transfers the idea to RUL regression and defines escalation by decision-region ambiguity"],
    ["L10", "Conformal Cascade: Distribution-Free Accuracy Guarantees for Multi-Tier LLM Inference", "Y. Dou; S. Lian; S. Li", 2026,
     "arXiv:2607.25018 (preprint)", "arXiv:2607.25018", "Multi-tier LLM cascades", "LLM QA benchmarks",
     "Defer unless conformal set is a singleton", "N", "N", "N", "N", "Y (conformal)", "N", "N", "Y", "P", "N",
     "LLM classification; union-bound guarantee. Basis: abstract",
     "Set-size deferral is the classification analogue of HERA's decision-sufficiency rule"],
    ["L11", "When Does Confidence-Based Cascade Deferral Suffice?", "W. Jitkrittum; N. Gupta; A. K. Menon; H. Narasimhan; et al.",
     2023, "NeurIPS 2023", "arXiv:2307.02764", "Theory of cascade deferral rules", "Image classification",
     "Confidence vs post-hoc deferral", "N", "N", "N", "N", "P (confidence)", "N", "N", "Y", "N", "N",
     "Generic ML. Basis: abstract", "Motivates comparing HERA's rule to confidence/width-only deferral"],
    ["L12", "Multi-Agent System-driven Digital Twins for predictive maintenance: architectures, technologies and open research challenges",
     "K. A. Coulibaly; M. Hamlich", 2026, "arXiv:2607.21873 (preprint, survey)", "arXiv:2607.21873",
     "Systematic review of MAS-DT for PdM", "Survey (547 papers)", "N/A", "Y", "Y", "Y", "P", "NR", "P", "P", "N", "NR", "NR",
     "Preprint survey. Basis: abstract", "Identifies hierarchical DT orchestration with residual-life estimation + XAI as open question"],
    ["L13", "AgenticTwin: An Agentic LLM Framework Integrated with Digital Twin for Anomaly Detection",
     "T. Hasan; M. Ghanta; S. Sarkar; U. Guin", 2026, "arXiv:2608.11679 (preprint)", "arXiv:2608.11679",
     "LLM explanations of DT anomalies", "NR", "DT anomaly classifier + LLM agent", "Y", "N", "Y", "N", "N", "Y", "Y", "N", "NR", "N",
     "Anomaly explanation, no prognosis. Basis: abstract", "Agents + DT + HIL exist; HERA keeps quantitative decisions in validated predictors"],
    ["L14", "Leveraging LLM Agents and Digital Twins for Fault Handling in Process Plants",
     "M. S. Gill; J. Vyas; A. Markaj; F. Gehlhoff; et al.", 2025, "IEEE ETFA 2025", "10.1109/ETFA65518.2025.11205597",
     "Fault handling via LLM agents with DT validation", "Process plant simulation", "LLM agents + DT", "Y", "N", "Y", "N", "N", "P", "P", "N", "NR", "N",
     "Control/fault handling, no RUL. Basis: arXiv abstract (2505.02076)", "Agentic DT prior art; not prognostics"],
    ["L15", "AI Agents and Agentic AI-Navigating a Plethora of Concepts for Future Manufacturing", "Y. Ren; Y. Liu; T. Ji; X. Xu",
     2025, "arXiv:2507.01376 (preprint, review)", "arXiv:2507.01376", "Concepts of agentic AI in manufacturing", "N/A", "N/A",
     "P", "N", "Y", "N", "N", "N", "P", "N", "N", "N", "Conceptual review. Basis: abstract", "Terminology for 'agents'"],
    ["L16", "A Multi-agent Digital Twin Framework for Predictive Maintenance Using Machine Learning and Genetic Algorithms: A Case Study Morocco, Tangier Med Port",
     "H. Garmouch; O. Abdoun", 2025, "Operations Research Forum 6", "10.1007/s43069-025-00579-x", "Port equipment PdM",
     "Case-study data (NR)", "ML + GA scheduling in multi-agent DT", "Y", "NR", "Y", "NR", "NR", "NR", "NR", "N", "NR", "NR",
     "Basis: title/search snippet only (paywalled)", "Agents + DT + PdM combination already published"],
    ["L17", "Multi-Agent Systems for Manufacturing Digital Twins: A Perspective on Agency and Large Language Models",
     "N. P. Greis; H. P. Cherukuri; J. C. M. Outeiro", 2025, "IFAC-PapersOnLine 59:1612-1617", "10.1016/j.ifacol.2025.09.271",
     "Perspective on MAS + LLM for DTs", "N/A", "N/A", "Y", "N", "Y", "N", "N", "N", "P", "N", "N", "N",
     "Perspective paper. Basis: title/snippet", "Positions agency in DTs"],
    ["L18", "An Agentic AI-based Architecture for Digital Twins Specialized in Predictive Maintenance: Application to Ball Mills",
     "C. Collao; H. Akhtar; C. Toro; C. Ocampo-Martinez", 2025, "IFAC-PapersOnLine 59:96-101", "10.1016/j.ifacol.2025.12.403",
     "Agentic DT for mill PdM", "Ball mill (NR)", "Agentic AI + DT", "Y", "NR", "Y", "NR", "NR", "NR", "NR", "N", "NR", "NR",
     "Basis: title only (abstract unavailable)", "Agentic DT PdM exists; confirms combination is not novel"],
    ["L19", "A Human-Centred Architecture Integrating Digital Twin and Agentic AI for Predictive Maintenance",
     "L. Mendonca; J. Barbosa; P. Leitao", 2026, "IEEE ICIT 2026, pp. 1-6", "10.1109/ICIT64854.2026.11491044",
     "Human-centred agentic DT PdM", "NR", "Agentic AI + DT", "Y", "NR", "Y", "NR", "NR", "NR", "Y", "N", "NR", "NR",
     "Basis: title only (abstract unavailable)", "Human-centric agentic DT PdM already proposed; HERA contribution must lie elsewhere"],
    ["L20", "A Safety-Constrained Agentic Digital Twin Framework for Predictive Maintenance in Smart Manufacturing Systems",
     "R. Sakha; S. Venkat; R. Sekaran; R. Vaithiyanathan", 2026, "ICDSBS 2026, pp. 1-5", "10.1109/ICDSBS69077.2026.11634862",
     "Safety filtering of agent actions", "NR", "Three-valued safety test; sensor reliability weight", "Y", "N", "Y", "NR", "P (sensor reliability)", "N", "N", "N", "NR", "N",
     "Basis: abstract", "Safety gating of agent actions exists; not statistically calibrated"],
    ["L21", "Agentic AI in Smart Manufacturing: Enabling Human-Centric Predictive Maintenance Ecosystems",
     "A. Fernandez-Miguel; S. Ortiz-Marcos; M. Jimenez-Calzado; A. P. Fernandez del Hoyo", 2025, "Applied Sciences 15:11414",
     "10.3390/app152111414", "Agentic PdM ecosystem", "Ceramic plant (proprietary)", "Federated learning, edge agents, XAI",
     "N", "Y", "Y", "NR", "P (trust calibration)", "Y", "Y", "N", "NR", "NR", "Proprietary data; not reproducible. Basis: abstract",
     "Agentic + edge + human oversight exists; no RUL interval routing"],
    ["L22", "Edge-Cloud Intelligent Fusion for Digital Twin-based Predictive Maintenance in Smart Manufacturing Systems",
     "L. Natrayan", 2026, "ICOSAAS 2026, pp. 513-519", "10.1109/ICOSAAS68663.2026.11649395", "DT PdM classification",
     "C-MAPSS", "Anomaly-score feature fusion at edge and cloud", "Y", "Y", "N", "N", "N", "N", "N", "N", "NR", "NR",
     "Classification accuracy only. Basis: abstract", "Edge-cloud DT PdM without UQ"],
    ["L23", "Conformal Prediction Intervals for Remaining Useful Lifetime Estimation", "A. Javanmardi; E. Hullermeier", 2023,
     "International Journal of Prognostics and Health Management 14(2)", "10.36001/ijphm.2023.v14i2.3417",
     "Conformalizing RUL point predictors", "C-MAPSS", "CNN, gradient boosting + split/normalized CP", "N", "N", "N", "Y", "Y (conformal)", "N", "N", "N", "N", "N",
     "No decision layer or system integration. Basis: abstract (arXiv 2212.14612)", "Foundation for HERA's calibration layer"],
    ["L24", "Uncertainty-Aware Bearing Remaining Useful Life Prediction Based on Conformal Prediction", "S. Wang; Y. Vidal; F. Pozo",
     2026, "PHM Society European Conference 9(1)", "10.36001/phme.2026.v9i1.4902", "Bearing RUL with calibrated intervals",
     "XJTU-SY", "VAE health index + monotone Transformer + MC dropout + conformal", "N", "N", "N", "Y", "Y (conformal)", "N", "N", "N", "N", "N",
     "Raw MC-dropout under-covers (48%), conformal restores ~94%; no decision/escalation. Basis: abstract",
     "Confirms conformal bearing RUL is established; HERA's novelty is not the calibration itself"],
    ["L25", "A General Data-Driven Framework for Remaining Useful Life Estimation with Uncertainty Quantification Using Split Conformal Prediction",
     "W. Xu; E. Zio", 2023, "ICSRS 2023, pp. 67-74", "10.1109/ICSRS59833.2023.10381131", "Adaptive conformal RUL intervals",
     "NR (abstract)", "Split conformal for single-point estimators", "N", "N", "N", "Y", "Y (conformal)", "N", "N", "N", "N", "N",
     "Basis: abstract", "Conformal RUL prior art"],
    ["L26", "Turbofan Engine Remaining Useful Life Prediction with Reliable Prediction Intervals via LSTM-Based Quantile Regression and Conformal Calibration",
     "R. Diao; M. Zhou; G. Meng; S. Wang", 2026, "Sensors 26:2249", "10.3390/s26072249", "RUL intervals via LSTM-QR + CQR",
     "C-MAPSS", "LSTM quantile regression + CQR", "N", "N", "N", "Y", "Y (CQR)", "N", "N", "N", "N", "N", "Basis: abstract",
     "Same calibration family as HERA (CQR); no hierarchy/decision gating"],
    ["L27", "A benchmark on uncertainty quantification for deep learning prognostics", "L. Basora; A. Viens; M. Arias Chao; X. Olive",
     2025, "Reliability Engineering & System Safety 253:110513", "10.1016/j.ress.2024.110513", "Benchmark of UQ methods for RUL",
     "N-CMAPSS (NR in abstract)", "BNN, MC dropout, deep ensembles, heteroscedastic NN", "N", "N", "N", "Y", "Y (Bayesian/ensemble)", "N", "N", "N", "N", "N",
     "Basis: search snippet", "Motivates calibration checks; uncalibrated UQ can be unreliable"],
    ["L28", "Uncertainty-aware remaining useful life prediction for predictive maintenance using deep learning",
     "Q. Le Xuan; Y. G. Adhisantoso; M. Munderloh; J. Ostermann", 2023, "Procedia CIRP 118:116-121", "10.1016/j.procir.2023.06.021",
     "Aleatoric + epistemic RUL uncertainty", "NR (abstract)", "Deep learning with confidence intervals", "N", "N", "N", "Y", "Y", "N", "N", "N", "N", "N",
     "Basis: abstract", "UQ used for reporting, not control"],
    ["L29", "Robust uncertainty quantification for online remaining useful life prediction with randomly missing and partially faulty sensor data",
     "W. Wang; Z. Wang; Z. Cai; C. Hu; et al.", 2025, "Reliability Engineering & System Safety 262:111177", "10.1016/j.ress.2025.111177",
     "Online RUL UQ under sensor faults", "NR", "NR", "N", "N", "N", "Y", "Y", "N", "N", "N", "NR", "N", "Basis: title/snippet", "Online UQ robustness; complementary"],
    ["L30", "Predictive maintenance optimization for industrial equipment via reliable prognosis and risk-aware reinforcement learning",
     "Z. Xu; Q. Zhang", 2025, "Complex & Intelligent Systems 12", "10.1007/s40747-025-02127-w", "Risk-aware maintenance decisions from probabilistic RUL",
     "NR (abstract)", "Probabilistic NN + QR-DQN agent", "N", "N", "P (single RL agent)", "Y", "Y (probabilistic)", "N", "N", "N", "N", "N",
     "Centralized; uncertainty feeds decisions but not compute routing. Basis: abstract",
     "Closest 'uncertainty drives maintenance decision' work; HERA additionally uses it to route computation"],
    ["L31", "Interpretable ensemble remaining useful life prediction enables dynamic maintenance scheduling for aircraft engines",
     "H. Ozcan", 2025, "Scientific Reports 15", "10.1038/s41598-025-23473-2", "RUL + threshold-based scheduling", "C-MAPSS",
     "LightGBM/CatBoost/GB ensemble", "N", "N", "N", "Y", "N", "Y", "N", "N", "N", "N", "Point-threshold scheduling (tau = 15 cycles). Basis: abstract",
     "Represents the fixed-threshold point-estimate baseline HERA is compared against"],
    ["L32", "Human-in-the-Loop XAI for Predictive Maintenance: A Systematic Review of Interactive Systems and Their Effectiveness in Maintenance Decision-Making",
     "N. R. Amaliah; B. Tjahjono; V. Palade", 2025, "Electronics 14:3384", "10.3390/electronics14173384", "Review of HITL-XAI in PdM",
     "63 studies", "N/A", "N", "N", "N", "P", "N", "Y", "Y", "N", "N", "N", "Review. Basis: abstract", "Supports HIL design choices"],
    ["L33", "Predictive maintenance for industry 5.0: behavioural inquiries from a work system perspective",
     "B. van Oudenhoven; P. Van de Calseyde; R. Basten; E. Demerouti", 2023, "International Journal of Production Research 61:7846-7865",
     "10.1080/00207543.2022.2154403", "Acceptance of PdM advice by decision makers", "Literature synthesis", "Work-system model",
     "N", "N", "N", "N", "N", "N", "Y", "N", "N", "N", "Behavioural, no algorithm. Basis: abstract",
     "Motivates advisory (not autonomous) high-impact actions"],
    ["L34", "From predictive maintenance 4.0 to 5.0: bringing humans back into the loop with a self-learning platform and implementation roadmap on automated production lines",
     "L. Lucantoni; F. E. Ciarapica; M. Bevilacqua", 2026, "Journal of Quality in Maintenance Engineering 32:58-75",
     "10.1108/JQME-12-2025-0147", "PdM 5.0 platform", "Automotive plant (proprietary)", "Probabilistic failure forecasts + XAI dashboards",
     "N", "NR", "N", "N", "P (probabilistic forecasts)", "Y", "Y", "N", "NR", "NR", "Industrial case study, not reproducible. Basis: abstract",
     "Human-centric PdM exists; no hierarchical routing"],
    ["L35", "Technician 5.0: A Hybrid Framework Integrating Chatbot, Digital Twin, and Machine Learning for Human-Centric Predictive Maintenance in Industry 5.0",
     "M. Masmoudi; M. Guerroum; H. Mahfoud", 2026, "Advanced Architectures and Techniques for Smart Industry, pp. 221-243",
     "10.1007/978-981-95-5271-9_9", "Chatbot + DT + ML for technicians", "NR", "ML + chatbot", "Y", "NR", "N", "NR", "NR", "P", "Y", "N", "NR", "NR",
     "Basis: title/snippet", "Human-centric DT PdM with conversational layer"],
    ["L36", "Prediction of bearing remaining useful life based on a two-stage updated digital twin",
     "D. He; J. Zhao; Z. Jin; C. Huang; et al.", 2025, "Advanced Engineering Informatics 65:103123", "10.1016/j.aei.2025.103123",
     "DT-driven bearing RUL", "Bearing run-to-failure (NR)", "Mechanism model + Bi-LSTM mapping", "Y", "N", "N", "Y", "NR", "N", "N", "N", "NR", "N",
     "Physics-based DT, centralized. Basis: search snippet", "DT-based bearing RUL; HERA's twin is a lightweight synchronized state"],
    ["L37", "Estimation of Bearing Remaining Useful Life Based on Multiscale Convolutional Neural Network", "J. Zhu; N. Chen; W. Peng",
     2019, "IEEE Transactions on Industrial Electronics 66:3208-3216", "10.1109/TIE.2018.2844856", "Bearing RUL",
     "Bearing degradation data (dataset NR in abstract)", "Wavelet TFR + multiscale CNN", "N", "N", "N", "Y", "N", "N", "N", "N", "N", "N", "Point estimates only. Basis: abstract",
     "Deep bearing RUL baseline family"],
    ["L38", "Long Short-Term Memory Network for Remaining Useful Life estimation", "S. Zheng; K. Ristovski; A. Farahat; C. Gupta",
     2017, "IEEE ICPHM 2017, pp. 88-95", "10.1109/ICPHM.2017.7998311", "RUL with LSTM", "C-MAPSS (other sets NR here)",
     "LSTM", "N", "N", "N", "Y", "N", "N", "N", "N", "N", "N", "Point estimates. Basis: title and DOI record", "Recurrent RUL baseline family"],
    ["L39", "A Robust Conformal Framework for IoT-Based Predictive Maintenance", "A. Moccardi; C. Conte; R. C. Ghosh; F. Moscato",
     2025, "Future Internet 17:244", "10.3390/fi17060244", "Conformal RUL confidence intervals for IoT PdM", "C-MAPSS",
     "SL/ML/DL predictors + naive, weighted and bootstrap conformal", "N", "N", "N", "Y", "Y (conformal)", "N", "N", "N", "N", "N",
     "No hierarchy or decision gating; recommends weighted conformal under non-exchangeability. Basis: abstract (found in final re-search)",
     "Directly relevant to HERA's coverage shortfall under between-bearing non-exchangeability"],
    ["L40", "Conformal selective prediction with cost aware deferral for safe clinical triage under distribution shift", "Kwon; Kim",
     2026, "Scientific Reports", "10.1038/s41598-026-40637-w", "Conformal deferral in clinical triage", "Clinical data (NR)",
     "Calibrated probabilities + conformal sets + cost-aware deferral", "N", "N", "N", "N", "Y (conformal)", "NR", "Y (defer to clinician)", "Y", "N", "N",
     "Medical classification; basis: title and search snippet (final re-search)", "Decision-aware conformal deferral exists outside PdM"],
    ["L41", "Online Conformal Probabilistic Numerics via Adaptive Edge-Cloud Offloading", "Q. Hou; S. Park; M. Zecchin; Y. Cai; G. Yu; O. Simeone",
     2025, "arXiv:2503.14453 (preprint)", "arXiv:2503.14453", "Calibrated edge solver sets with adaptive offloading", "Linear systems",
     "Probabilistic linear solver + online conformal calibration", "N", "Y", "N", "N", "Y (online conformal)", "N", "N", "Y", "P", "N",
     "Not PdM. Basis: abstract (final re-search)", "Conformal edge-cloud offloading is an active general topic"],
    ["L42", "CR^2: Cost-Aware Risk-Controlled Routing for Wireless Device-Edge LLM Inference", "N. Xue; S. Chen; Z. Chen; J. Yao; Y. Sun; Z. Hu; M. Tao",
     2026, "arXiv:2605.12001 (preprint)", "arXiv:2605.12001", "Risk-controlled device-edge routing for LLMs", "LLM benchmarks",
     "Two-stage cost-aware router with risk control", "N", "Y", "N", "N", "P (risk control)", "N", "N", "Y", "Y", "P",
     "Not PdM. Basis: abstract (final re-search)", "Risk-controlled routing on edge; different domain and task"],
]


def main():
    out = Path(__file__).parent / "literature_matrix.csv"
    with out.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(COLS)
        for r in R:
            assert len(r) == len(COLS), r[0]
            w.writerow(r)
    print(f"wrote {len(R)} papers -> {out}")


if __name__ == "__main__":
    main()
